# This is a basic workflow to help you get started with Actions

name: deploy app1

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    paths:
      - apps/app1/**
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build app1
        run: echo 'build app1 in deploy-app1'

      # Runs a set of commands using the runners shell
      - name: deploy app1
        run: echo 'deploy app1 in deploy-app1'
