# This is a basic workflow to help you get started with Actions

name: base ci/cd

# Controls when the workflow will run
on:
  push:
    paths:
      - "apps/base"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build all
        run: echo 'build all in deploy-app'

      # Runs a set of commands using the runners shell
      - name: deploy all
        run: echo 'deploy all in deploy-app'
